// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the build information for the
// receiver/splunktail component.
package metadata

import "go.opentelemetry.io/collector/component"

var (
	Type      = component.MustNewType("splunktail")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/splunktailreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
