// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the build information for the
// exporter/splunktcpout component.
package metadata

import "go.opentelemetry.io/collector/component"

var (
	Type      = component.MustNewType("splunktcpout")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunktcpoutexporter"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
